version: "3"
services:
  app:
    build: .
    env_file:
      - .env
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./.:/app/.

  db:
    image: mysql:latest
    env_file:
      - .env
    ports:
      - "3307:3307"
    environment:
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - data-volume:/var/lib/mysql:rw,delegated

volumes:
  data-volume:
